FROM python:3.11.6

WORKDIR /auth_api_1

COPY ./requirements.txt ./requirements.txt

RUN  pip install --upgrade pip \
     && pip install -r requirements.txt --no-cache-dir

EXPOSE 8000

COPY start.sh /

RUN chmod +x /start.sh

ENTRYPOINT ["/start.sh"]